services:
  app:
    build: .
    container_name: touristic_destinations_app_dev
    ports:
      - '${PORT:-3000}:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-touristic_destinations}
    volumes:
      - .:/usr/src/app # mount the whole project in container, so if any file change it will be sync with the container
      - /usr/src/app/node_modules # Node modules are preserved so the container has the most compatible ones
    command: npm run start:dev
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: touristic_destinations_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-touristic_destinations}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
